docker-compose.yml, webapp/src/api.ts, webapp/src/components/InviteForm.tsx, webapp/src/controllers/team.ts, webapp/src/db/team.ts, webapp/src/pages/[resourceSlug]/team.tsx, webapp/src/router.ts
DO NOT PULL. Need to LINT first
=> #93 enabled removal of team member (and invited team member)

CONTRIBUTING.md
Added changes in our contributing guide
=> Made changes in our CONTRIBUTING.md

.gitignore, agent-backend/src/build/build_crew.py, agent-backend/src/models/mongo.py
The problem was that models in `agent_backend` were not updated after adding the `embedding` model type property in mongo. I changed the Pydantic models slightly to accommodate this update, and then pick the correct OpenAI model depending on this property.
=> Fix for RAG not working for OpenAI models

agent-backend/src/models/mongo.py, agent-backend/src/tools/rag_tool.py, agent-backend/src/tools/retrievers/base.py, agent-backend/src/tools/retrievers/callback_handler.py, agent-backend/src/tools/retrievers/custom/time_weighted_retriever.py, agent-backend/src/tools/retrievers/default.py, agent-backend/src/tools/retrievers/multi_query.py, agent-backend/src/tools/retrievers/self_query.py, agent-backend/src/tools/retrievers/similarity_search.py, agent-backend/src/tools/retrievers/time_weighted.py
- Added `RetrieverCallbackHandler` to handle `on_retriever_start`, `on_retriever_end` and `on_retriever_error` events
- Refactored `BaseToolRetriever` a bit, and also broke up DefaultRetriever to use a separate `SimilaritySearchRetriever`
=> #176 Improve RAG debug logs

webapp/src/lib/middleware/auth/usesession.ts
https://github.com/rnadigital/agentcloud/issues/80
Added secure flag in express session based on dev/prod mode
=> feature-80 : added flag for secure session

agent-backend/poetry.lock, agent-backend/pyproject.toml, agent-backend/src/tools/builtin_tools.py, agent-backend/src/tools/builtins/__init__.py, agent-backend/src/tools/builtins/duckduckgo.py, agent-backend/src/tools/builtins/stackexchange.py, agent-backend/src/tools/builtins/youtube.py, webapp/src/lib/struct/globaltools.ts
Added:
- DuckDuckGo Search,
- StackExchange, and
- Youtube
=> Add few more builtin tools

README.md
Adding MongoDB Blog in README.md
=> Adding MongoDB Blog in README.md

README.md
Added new blog post in README.md
=> Added new blog post in README.md

agent-backend/src/tools/rag_tool.py, agent-backend/src/tools/retrievers/base.py, agent-backend/src/tools/retrievers/self_query.py, agent-backend/src/tools/retrievers/similarity_search.py
... for similarity_search, self_query and multi_query retrieval strategies
=> Return relevance scores in retriever results

agent-backend/poetry.lock, agent-backend/pyproject.toml, agent-backend/src/lang_models/factory.py, agent-backend/src/models/mongo.py, webapp/src/components/ModelForm.tsx, webapp/src/components/SimpleAppForm.tsx, webapp/src/lib/struct/credential.ts, webapp/src/lib/struct/model.ts
... support for `LLaMA3 70b` and `Mixtral 8x7b`
=> Add Groq chat models

webapp/src/components/CreateDatasourceForm.tsx, webapp/src/components/DatasourceScheduleForm.tsx, webapp/src/components/DatasourceTabs.tsx, webapp/src/controllers/datasource.ts, webapp/src/db/datasource.ts, webapp/src/lib/struct/datasource.ts, webapp/src/lib/struct/schedule.ts, webapp/src/pages/[resourceSlug]/datasource/[datasourceId]/index.tsx
Remove some unused imports in datasource controller Fix updateDatasource call creating a nested object with the connection body under "datasource" Hide some tabs and fix the schedule editing tab
Remove BASICSCHEDULE fron frontend because airbyte new API doesn't support it yet (its just cron anyway) close #264
=> Move DatasourceScheduleType to datasources struct

webapp/src/controllers/datasource.ts, webapp/src/controllers/model.ts, webapp/src/controllers/session.ts, webapp/src/controllers/stripe.ts, webapp/src/controllers/task.ts, webapp/src/controllers/team.ts, webapp/src/controllers/tool.ts
Add request body validation for session, stripe, task, team and tool form submission
Fixed form validation issues in datasource and model
=> Add request validations

agent-backend/poetry.lock, agent-backend/pyproject.toml, agent-backend/src/chat/chat_assistant.py, agent-backend/src/tools/builtins/base.py, agent-backend/src/tools/global_tools.py, agent-backend/src/tools/retrievers/self_query.py
Merge only after merging `crewAI` upgrade
=> CrewAI + langchain upgrade changes

agent-backend/src/lang_models/factory.py, agent-backend/src/utils/dict_utils.py, webapp/src/components/ChatAppForm.tsx, webapp/src/components/ModelForm.tsx, webapp/src/components/models/ModelTypeRequirements.tsx, webapp/src/controllers/app.ts, webapp/src/lib/struct/model.ts
Frontend works and allows creation of vertex models now.
Getting an error when I try to run it, not sure if I have wrong creds or if it's something that needs fixing in process app logic:
<details>
<summary>snip</summary>
```
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1721955181.337070 2617129 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache
2024-07-26 10:53:01,479 - 127319538665152 - _plugin_wrapping.py-_plugin_wrapping:109 - ERROR: AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x73cc30543bf0>" raised exception! …
```
=> Vertex model support

webapp/src/controllers/account.ts, webapp/src/lib/account/create.ts, webapp/src/pages/verify.tsx
cc @anada10 when this is merged, also go to:
https://dashboard.stripe.com/pricing-tables/prctbl_1PgMpbBf4G7FMeKpxkXfd0oT/edit?productId=prod_QTcfenYXWsj1Fd
and update the confirmation page url:
make it:
`https://app.agentcloud.dev/verify?checkoutsession={CHECKOUT_SESSION_ID}`
=> Fix stripe flow so users have to click email link to verify the account

webapp/src/components/SharingModeSelect.tsx, webapp/src/lib/struct/billing.ts, webapp/src/router.ts
=> Limit public ap sharing to teams and/or enterprise only

webapp/src/components/CrewAppForm.tsx
=> Set default verbose to 0

webapp/src/components/TaskForm.tsx, webapp/src/controllers/task.ts, webapp/src/lib/struct/task.ts, webapp/src/pages/[resourceSlug]/task/[taskId]/edit.tsx, webapp/src/pages/[resourceSlug]/task/add.tsx
=> Add context to taskform

webapp/src/pages/[resourceSlug]/task/[taskId]/edit.tsx
=> Set taskchoices to [] when tasks is undefined

webapp/src/components/ConfirmModal.tsx, webapp/src/components/CreateDatasourceModal.tsx, webapp/src/components/CreateTaskModal.tsx, webapp/src/components/DatasourceStream.tsx, webapp/src/components/DeleteModal.tsx, webapp/src/components/DropZone.tsx, webapp/src/components/SubscriptionModal.tsx, webapp/src/pages/[resourceSlug]/datasource/[datasourceId]/index.tsx, webapp/src/pages/verify.tsx
Add dark theme styling to pages and modals
=> Add dark theme styling to pages and modals

webapp/src/components/AvatarUploader.tsx
Only allow images to be uploaded
=> Only allow images to be uploaded

webapp/src/components/Layout.tsx, webapp/src/context/themecontext.tsx, webapp/src/pages/_document.tsx
Fix light flickering on page load
=> Fix light flickering on page load

webapp/src/components/Layout.tsx, webapp/src/context/themecontext.tsx, webapp/src/pages/_document.tsx
Reverts rnadigital/agentcloud#397
=> Revert "Fix light flickering on page load"

webapp/src/pages/_document.tsx
=> By default set theme to light

agent-backend/src/crew/build_crew.py
=> Add try except block to handle validation errors

webapp/src/components/CreateDatasourceForm.tsx
@anada10 hit merge if you're happy with how it looks.
=> 412 datasource badges

webapp/src/components/CreateDatasourceForm.tsx, webapp/src/components/SubscriptionModal.tsx, webapp/src/context/account.tsx, webapp/src/context/chat.tsx
add which connector in datasource connector upgrade modal call closes #417
=> add values in cohort calls

webapp/src/components/TaskForm.tsx
Move the "new" button to the first option, like other dropdowns with an add new option
=> Fix clearing the preferred agent dropdown opening the new agentform

webapp/src/components/CreateDatasourceForm.tsx, webapp/src/components/CreateDatasourceModal.tsx, webapp/src/pages/[resourceSlug]/datasource/add.tsx, webapp/src/pages/[resourceSlug]/datasources.tsx
=> Adding modal when exiting datasource creation

vector-db-proxy/src/adaptors/mongo/models.rs, vector-db-proxy/src/data/unstructuredio/apis.rs, vector-db-proxy/src/data/unstructuredio/models.rs, vector-db-proxy/src/messages/tasks.rs, vector-db-proxy/src/utils/file_operations.rs, webapp/src/components/CreateDatasourceForm.tsx, webapp/src/components/DatasourceChunkingForm.tsx, webapp/src/components/DropZone.tsx, webapp/src/components/RetrievalStrategyComponent.tsx, webapp/src/components/tools/ToolForm.tsx, webapp/src/controllers/datasource.ts, webapp/src/lib/struct/datasource.ts, webapp/src/migrations/1.6.0.ts
@ragyabraham try branch `413-new-chunking-strategies` , it sets a `chunkingConfig` on file upload datasources with all the options you need for unstructured chunking and partitioning:
=> 413 new chunking strategies

agent-backend/src/crew/build_crew.py, agent-backend/src/models/mongo.py, agent-backend/src/utils/json_schema_to_pydantic.py, webapp/src/components/Editor.tsx, webapp/src/components/TaskForm.tsx, webapp/src/components/chat/message.tsx, webapp/src/controllers/task.ts, webapp/src/lib/struct/task.ts, webapp/src/pages/[resourceSlug]/task/add.tsx, webapp/src/pages/[resourceSlug]/tool/add.tsx, webapp/src/socketio.ts
enhancement, bug fix
___
- Added JSON validation for structured output schema in `ScriptEditor`.
- Introduced structured output toggle and JSON editor in `TaskForm`.
- Improved message handling for JSON content in chat and socket communication.
- Added `isStructuredOutput` handling in task creation and editing APIs.
- Created utility for converting JSON schema to Pydantic model.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><details><summary>8 files</summary><table>
<tr>
<td>
<details>
<summary><strong>Editor.tsx</strong><dd><code>Add JSON validation and language prop to ScriptEditor</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
webapp/src/components/Editor.tsx
<li>Added JSON validation for …
=> 461 structured output

webapp/src/components/TaskForm.tsx
FIxes this issue
1. Create new task
2. Type expected output
3. Expected output field returns blank
=> Correct the condition to setExpectedOutput to blank string

webapp/src/api.ts, webapp/src/components/InviteForm.tsx, webapp/src/components/MemberList.tsx, webapp/src/components/PermissionsEditor.tsx, webapp/src/components/SubscriptionModal.tsx, webapp/src/controllers/app.ts, webapp/src/controllers/model.ts, webapp/src/controllers/org.ts, webapp/src/controllers/session.ts, webapp/src/controllers/team.ts, webapp/src/db/account.ts, webapp/src/db/org.ts, webapp/src/db/team.ts, webapp/src/lib/middleware/auth/usejwt.ts, webapp/src/lib/permissions/Permission.ts, webapp/src/lib/permissions/roles.ts, webapp/src/pages/[resourceSlug]/org.tsx, webapp/src/pages/[resourceSlug]/team.tsx, webapp/src/router.ts, webapp/src/socketio.ts, webapp/src/test/account.ts, webapp/src/test/integration.test.ts, webapp/src/test/models.ts, webapp/src/test/teams.ts
- Change permission editing screen to update when changing role
- only allow custom permission changing when on enterprise plan
=> org permissions updates

webapp/package-lock.json, webapp/package.json, webapp/src/components/Layout.tsx, webapp/tailwind.config.js
- Added custom scrollbar styling to the sidebar
- Integrated `tailwind-scrollbar` plugin into the Tailwind CSS configuration.
=> Improve sidebar scrollbar styling

webapp/src/controllers/model.ts, webapp/src/test/account.ts, webapp/src/test/integration.test.ts, webapp/src/test/logout.ts, webapp/src/test/models.ts, webapp/src/test/pages.ts, webapp/src/test/teams.ts
=> 567 more e2e tests

agent-backend/.gitignore, agent-backend/src/tools/builtin_tools.py, agent-backend/src/tools/builtins/__init__.py, agent-backend/src/tools/builtins/firecrawl_loader.py, webapp/src/lib/struct/globaltools.ts
This uses the langchain implementation of the firecrawl loader instead of the native crewAI one, seems like all tools use the langchain tools
=> New tool, simple html loader using firecrawl loader

webapp/package-lock.json, webapp/package.json, webapp/src/db/index.ts, webapp/src/lib/struct/datasource.ts, webapp/src/lib/struct/vectordb.ts, webapp/src/server.ts
- Added Mongoose as a new database connection library, including setup and error handling for connections.
- Defined Mongoose schemas and models for `Datasource` and `VectorDb`, facilitating structured data handling.
- Integrated Mongoose connection into the server initialization process.
- Updated project dependencies to include Mongoose and related packages, ensuring compatibility and functionality.
=> Add Mongoose Schema for Vectordb and Datasource Models

docker-compose.yml, install.sh
Slightly modifying docker-compose.yml and install.sh to account for potential issues on linux systems when developing codebase.
(I'm not 100% sure if these changes are needed or not but this is what I had to change to get airbyte working locally for myself, if these changes don't address any issues on prod then delete the branch and don't worry about them)
=> docker-compose and install.sh changes

agent-backend/src/crew/build_crew.py, vector-db-proxy/src/adaptors/qdrant/apis.rs, vector-db-proxy/src/adaptors/qdrant/helpers.rs
- Added logging for collection creation in `QdrantClient` to improve traceability.
- Improved UUID handling in `construct_point_struct` by cleaning extra backslashes and validating UUID format.
- Commented out the `wrap_rag_tool_with_agent_llm` function in `build_crew.py`, disabling the wrapping of RAG tools with agent LLM. (users should alway use good descriptions for tasks and datasources to avoid string schema errors)
=>   Improve UUID Handling

webapp/src/pages/[resourceSlug]/vectordbs.tsx
- Added conditional logic to display the "New Vector DB" button only when there are existing vector databases.
- Updated button message from "Add Variable" to "Add Vector DB" for clarity.
=>   Conditionally Display "New Vector DB" Button and Update Button Message

webapp/src/components/Layout2.tsx, webapp/src/components/TrialNag.tsx
=> remove duplicate trial nag

webapp/src/lib/account/create.ts
- Added `await` to `render` function calls for email templates.
- Ensured asynchronous rendering for both invite and verification emails.
=> Add await to email template rendering

webapp/src/pages/billing.tsx
=> redirect to stripe billing

webapp/src/components/connections/DataSourceGrid.tsx, webapp/src/pages/[resourceSlug]/connections/add.tsx
- Replaced the `findIndexToDisplayForm` function with direct conditional logic.
- Updated the page title in the `AddConnection` component to "Add Connection".
=>   Refactor DataSourceGrid form rendering and update AddConnection title

webapp/src/components/connections/DataSourceGrid.tsx, webapp/src/pages/[resourceSlug]/connections/add.tsx
- Make DataSourceGrid items responsive width
- Apply responsive padding in AddConnection page
=>   Improve responsive layout for AddConnection UI

webapp/src/components/AgentList.tsx, webapp/src/components/AgentList2.tsx, webapp/src/components/DatasourceStream.tsx, webapp/src/components/agents/NewAgentSheet.tsx, webapp/src/modules/components/connections/Streams.tsx, webapp/src/modules/components/multi-select.tsx
- Rename `NewAgentSheet` to `AgentSheet`, unify new/edit logic
- Add edit action and selectedAgent state in `AgentList2`
=> Add edit agents feature

webapp/src/components/DatasourceStream.tsx, webapp/src/modules/components/connections/Streams.tsx
- Updated StreamsList to filter streams based on the presence of checked children in their initial state,
=> Refactor StreamsList to display only selected stream

webapp/src/components/apps/crew-apps/AgentSelection.tsx, webapp/src/components/connections/LLMConfigurationForm.tsx, webapp/src/pages/[resourceSlug]/session/[sessionId]/index.tsx
- Simplified the construction of model lists by ensuring consistent formatting and removing unnecessary conditional checks.
=> Refactor LLMConfigurationForm f

webapp/src/components/DropZone.tsx, webapp/src/components/agents/NewAgentSheet.tsx, webapp/src/components/connections/DataSourceDetails.tsx, webapp/src/components/connections/DataSourceGrid.tsx, webapp/src/components/connections/DatasourceStream.tsx, webapp/src/components/connections/DatasourceStreamConfiguration.tsx, webapp/src/components/connections/DatasourceSyncing.tsx, webapp/src/components/connections/EmbeddingModelSelect.tsx, webapp/src/components/connections/VectorDBSelection.tsx, webapp/src/components/connectorform/AdditionalFields.tsx, webapp/src/components/connectorform/DynamicConnectorForm.tsx, webapp/src/components/connectorform/FormField.tsx, webapp/src/components/connectorform/FormSection.tsx, webapp/src/components/onboarding/DataSourceDetails.tsx, webapp/src/components/onboarding/VectorDBSelection.tsx, webapp/src/context/connectorform.tsx, webapp/src/context/onboardingform.tsx, webapp/src/hooks/useFormPersistence.ts, webapp/src/pages/[resourceSlug]/connections/add.tsx, webapp/src/store/datasource.ts
- Add form persistence via custom hook
- Persist datasource, stream, and model selections
- Reset and restore form state automatically
- Add Back buttons and UI cleanup
=> Maintain state during datasource creation

webapp/src/pages/[resourceSlug]/session/[sessionId]/index.tsx
Remove unused logging statements in Session component
=> Remove unused logging statements in Session component

agent-backend/src/init/env_variables.py
Update LOG_LEVEL environment variable handling to ensure a default value is set correctly
=> Update LOG_LEVEL environment variable handling to ensure a default value is set correctly

agent-backend/src/main.py
Enable debug and verbose logging by default in main.py
=> Enable debug and verbose logging by default in main.py

agent-backend/src/main.py, agent-backend/src/models/sockets.py, agent-backend/src/redisClient/utilities.py, agent-backend/src/tools/code_execution_docker_notebook_tool.py, agent-backend/src/tools/code_execution_tool.py, agent-backend/src/tools/google_cloud_function.py, agent-backend/src/tools/rag_tool.py, agent-backend/src/tools/retrievers/base.py, agent-backend/src/tools/retrievers/custom/time_weighted_retriever.py, agent-backend/src/vectorstores/factory.py
- Configure logging in main.py to handle Unicode characters properly.
- Update JSON serialization in SocketMessage to ensure UTF-8 encoding.
- Modify RedisClass to use UTF-8 encoding for JSON data.
- Improve error handling for Unicode decoding in code execution tools.
- Ensure consistent Unicode-safe printing in various retrievers and tools.
- Refactor code for better readability and maintainability.
=> Enhance Unicode handling across the application

agent-backend/Dockerfile, agent-backend/src/main.py, agent-backend/src/models/sockets.py, agent-backend/src/redisClient/utilities.py, agent-backend/src/tools/code_execution_docker_notebook_tool.py, agent-backend/src/tools/code_execution_tool.py, agent-backend/src/tools/google_cloud_function.py, agent-backend/src/tools/rag_tool.py, agent-backend/src/tools/retrievers/base.py, agent-backend/src/tools/retrievers/custom/time_weighted_retriever.py, agent-backend/src/vectorstores/factory.py
- Remove custom Unicode error handling and `ensure_ascii` flags
- Simplify JSON dumps and string decoding across modules
- Standardize string quoting and formatting conventions
- Add UTF-8 environment variables to Dockerfile
=>   Simplify Unicode handling and update Docker encoding
